### ISSUE TITLE
Support older versions of Node

### ISSUE THREAD

**Issue by vassyz** [getyoti/node#3]
Because the key is unwrapped using the `Buffer.from` method, older versions of Node (something like 5.1 or 5.3, around late 2015) will not be supported. I don't have time to look into this right now, but I can investigate once I get back from holiday.

**Comment by rob-yoti** [comment]
@vassyz I only see the key unwrapped using `new Buffer` not `Buffer.from`.

Which file and line do you see 'Buffer.from` being used?
